apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cka-lab.io/owner: cka-talos-practice
    cka-lab.io/task: T08
  name: web
  namespace: __NAMESPACE__
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
        cka-lab.io/owner: cka-talos-practice
        cka-lab.io/task: T08
    spec:
      containers:
      - image: nginx:1.27-alpine
        name: web
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi
